### PR TITLE
allowing executions in different directories: issue #27

### PR DESCRIPTION
**Pull request by rpau**

### CODE REVIEW

**Comment by rpau** [comment]
@abelsromero I will merge if it is fine for you

**Comment by abelsromero** [comment]
Seems fine, but let me do some profiling tests tomorrow. I'll run them from your repo to be sure.

**Comment by abelsromero** [comment]
This solutions affects also how the configuration file is loaded making walkmod fail.
For instance, when doing this initialitzation:
```
	File executionDir = new File("src/test/resources/testFiles");
	File srcDir = new File(executionDir, "src/main/java");
	srcDir.mkdirs();
	FileUtils.write(new File(srcDir, "Bar.java"),	"public class Bar { private int foo; }");
        File cfg = new File("src/test/resources/test-cases/script/walkmod.xml");

	WalkModFacade facade = new WalkModFacade(cfg, OptionsBuilder.options()
				.executionDirectory(executionDir).printErrors(true), null);
```

Causes that at [XMLConfigurationProvider.java#L121](https://github.com/rpau/walkmod-core/blob/multimodule/src/main/java/org/walkmod/conf/providers/XMLConfigurationProvider.java#L121) `configFileName` contains the value `$SOME_PATH\walkmod-core\src\test\resources\testFiles\src\test\resources\test-cases\script\walkmod.xml`, thus incorrectly inserting the executionDir in the middle and causing an error, since the file is not found.

Passing and absolute path works.

**Comment by abelsromero** [comment]
A quick fix could be getting the absolute path as soon as possible. e.g. https://github.com/rpau/walkmod-core/blob/multimodule/src/main/java/org/walkmod/WalkModFacade.java#L269

**Pull request merged**
