### PR TITLE
fixes #32 adding the AppVeyor configuration file

### LINKED ISSUE #32: setup AppVeyour to test builds on Windows

### PR DESCRIPTION
**Pull request by abelsromero**
Stil, after merged the repo must be configured in the AppVeyor application.
It is required to:
* Go into https://ci.appveyor.com/
* Log with GitHub account
* Use the "New project" option to add the repo from the available ones
* (not mandatory) add badge to readme

With that it's all set, appveyor will triggle on PRs. It is slower than other CIs and it takes some time to start, sometimes even 20 minutes.

### CODE REVIEW

**Comment by rpau** [comment]
Hi, tests are not working properly on windows (https://ci.appveyor.com/project/rpau/walkmod-core/build/job/2tkd5b7d3mmjypkt). @abelsromero, can you see the log of the execution?

**Comment by abelsromero** [comment]
Yup, those test failed in my machine too but I wanted to be sure on AppVeyour before reporting.

* `testIncludes2(org.walkmod.util.FileResourceTest)` seems to have some issue related to paths
* `testEndLineChar(org.walkmod.writers.AbstractFileWriterTest)` has an issue with linebreaks, it seems that the returnet linebreak code for Windows is different.

Just typical Windows stuff...

I can have a look at them later. I have AppVeyour also on my fork, so I can execute there also without having to send a PR.

**Comment by abelsromero** [comment]
The second issue (`testEndLineChar(org.walkmod.writers.AbstractFileWriterTest)`) is pretty simple, the implementation here https://github.com/rpau/walkmod-core/blob/master/src/main/java/org/walkmod/writers/AbstractFileWriter.java#L216-L218, contradicts the test here https://github.com/rpau/walkmod-core/blob/master/src/test/java/org/walkmod/writers/AbstractFileWriterTest.java#L45-L47.
If the implementation is the right option, then it is as simple as changing the test code to `\r`.

**Comment by abelsromero** [comment]
For the first issue I saw that Paths are normalized to unix separators (e.g [here](https://github.com/rpau/walkmod-core/blob/master/src/main/java/org/walkmod/util/FileResource.java#L79-L8)). I just used the `normalize` method withouth boolean which uses the native OS separator and it works...seems to easy for me, but not a bad solution, or am i missing something?

**Comment by rpau** [comment]
I have tried to apply this changes in the multimodule branch, but the appveyor fails. May be I am doing something wrong. Anyway, I will check all again, but I have time limited because I am in a business travel during this week and the connection is limited. I will send my feedback this weekend.

**Comment by abelsromero** [comment]
Don't worry, I just did some quick test yesterday and see that you didn't see any problem. I'll look it in more detial and send a PR.

**Pull request merged**
